name: napari-mass-env
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - python=3.11
 - pyqt
 - napari>=0.5
 - numpy
 - scipy
 - scikit-image
 - scikit-learn
 - dask
 - tifffile>=2023.9.26
 - napari-ome-zarr
 - psutil
 - pyyaml
 - matplotlib
 - tqdm
 - pip
 - pip:
   - opencv-contrib-python-headless
